const fs = require("fs");
const path = require("path");
const target = path.join(__dirname, "findLevel018Bold.ts");
const lines = [];
const push = (s) => lines.push(s);
push("/**");
push(" * Level 18 Castle Moat: BFS for completion (bold 553s remaining).");
push(" */");
push('import fs from "node:fs";');
push('import path from "node:path";');
push('import { fileURLToPath } from "node:url";');
push('import { normalizeLevelLayers } from "../engine/levelLayers.js";');
push("import {");
push("  cloneMsCc1SimulationRunner,");
push("  createMsCc1SimulationRunner,");
push("  msCc1RunnerStateKey,");
push("  stepMsCc1Simulation,");
push('} from "../engine/msCc1/msCc1Simulation.js";');
push('import { msSecondsRemaining } from "../engine/msCc1/msCc1Timing.js";');
push('import { encodeSolutionMoves } from "../engine/solutionMoves.js";');
push('import type { Direction, LevelData } from "../engine/types.js";');
push("");
push("const __dirname = path.dirname(fileURLToPath(import.meta.url));");
push('const root = path.resolve(__dirname, "..");');
push("const TIME_LIMIT = 600;");
push("const BOLD_REMAINING = 553;");
push('const dirs: Direction[] = ["up", "down", "left", "right"];');
push("");
push("const level = JSON.parse(");
push("  fs.readFileSync(");
push("    path.join(");
push("      root,");
push('      "../chips-challenge-web/apps/chips-challenge-web/public/games/chips-challenge-1/levels/level-018.json",');
push("    ),");
push('    "utf8",');
push("  ),");
push(") as LevelData;");
push("normalizeLevelLayers(level);");
push("");
push("type Runner = ReturnType<typeof createMsCc1SimulationRunner>;");
push("");
push("function apply(start: Runner, seq: Direction[]): Runner {");
push("  const r = cloneMsCc1SimulationRunner(start);");
push("  for (const d of seq) {");
push("    stepMsCc1Simulation(r, d);");
push("    if (r.completed || r.playerDied) break;");
push("  }");
push("  return r;");
push("}");
push("");
push("function meetsBold(ticks: number): boolean {");
push("  return msSecondsRemaining(TIME_LIMIT, ticks) >= BOLD_REMAINING;");
push("}");
push("");
push("function maxBoldTicks(): number {");
push("  for (let t = 0; t <= 5000; t += 1) {");
push("    if (msSecondsRemaining(TIME_LIMIT, t + 1) < BOLD_REMAINING) return t;");
push("  }");
push("  return 5000;");
push("}");
push("");
push("const MAX_BOLD_TICKS = maxBoldTicks();");
push("");
push("function visitKey(runner: Runner, includeTicks: boolean): string {");
push("  const base = msCc1RunnerStateKey(runner);");
push("  if (includeTicks) return base;");
push('  const parts = base.split("|");');
push("  parts.pop();");
push("  parts.pop();");
push('  return parts.join("|");');
push("}");
push("");
push("type BfsResult = { seq: Direction[]; ticks: number; rem: number; bold: boolean };");
push("");
push("function bfs(");
push("  start: Runner,");
push("  maxDepth: number,");
push("  maxNodes: number,");
push("  done: (r: Runner) => boolean,");
push("  opts: { includeTicksInKey?: boolean; maxTicks?: number } = {},");
push("): BfsResult | null {");
push("  const includeTicks = opts.includeTicksInKey ?? false;");
push("  const maxTicks = opts.maxTicks;");
push("  const q: { seq: Direction[]; runner: Runner }[] = [{ seq: [], runner: start }];");
push("  const seen = new Set<string>([visitKey(start, includeTicks)]);");
push("  let n = 0;");
push("  let best: BfsResult | null = null;");
push("  while (q.length && n < maxNodes) {");
push("    const f = q.shift()!;");
push("    n++;");
push('    if (n % 500_000 === 0) console.log("  expanded", n, "depth", f.seq.length, "q", q.length);');
push("    if (done(f.runner)) {");
push("      const ticks = f.runner.buttonPressCtx.moveBoundary;");
push("      const rem = msSecondsRemaining(TIME_LIMIT, ticks);");
push("      if (maxTicks !== undefined && ticks > maxTicks) continue;");
push("      const hit: BfsResult = { seq: f.seq, ticks, rem, bold: meetsBold(ticks) };");
push("      if (!best || ticks < best.ticks) best = hit;");
push("      continue;");
push("    }");
push("    if (f.seq.length >= maxDepth || f.runner.playerDied) continue;");
push("    for (const d of dirs) {");
push("      const next = cloneMsCc1SimulationRunner(f.runner);");
push("      const before = visitKey(next, includeTicks);");
push("      stepMsCc1Simulation(next, d);");
push("      if (next.playerDied) continue;");
push("      if (maxTicks !== undefined && next.buttonPressCtx.moveBoundary > maxTicks) continue;");
push("      const after = visitKey(next, includeTicks);");
push("      if (after === before || seen.has(after)) continue;");
push("      seen.add(after);");
push("      q.push({ seq: [...f.seq, d], runner: next });");
push("    }");
push("  }");
push('  console.log("  nodes", n, "seen", seen.size);');
push("  return best;");
push("}");
push("");
push("function lettersToDirs(s: string): Direction[] {");
push('  const map: Record<string, Direction> = { L: "left", R: "right", U: "up", D: "down" };');
push('  return [...s.replace(/\\s/g, "")].map((c) => map[c]!).filter(Boolean);');
push("}");
push("");
push("function report(label: string, hit: BfsResult | null): BfsResult | null {");
push("  if (!hit) {");
push('    console.log(label, "NOT FOUND");');
push("    return null;");
push("  }");
push("  console.log(label, {");
push("    found: true,");
push("    moveCount: hit.seq.length,");
push("    ticks: hit.ticks,");
push("    secondsRemaining: hit.rem,");
push("    meetsBold: hit.bold,");
push("    moveString: encodeSolutionMoves(hit.seq),");
push("  });");
push("  return hit;");
push("}");
push("");
push("const startRunner = createMsCc1SimulationRunner(structuredClone(level));");
push('console.log("Level 18 Castle Moat", { start: [startRunner.gx, startRunner.gy], maxBoldTicks: MAX_BOLD_TICKS });');
push("");
push("let result: BfsResult | null = null;");
push('');
push('console.log("\\n=== Full BFS to exit ===");');
push("result = bfs(startRunner, 400, 6_000_000, (r) => r.completed, { includeTicksInKey: false });");
push('result = report("fullBfs", result);');
push("");
push("if (!result) {");
push('  console.log("\\n=== Segmented: flippers then exit ===");');
push("  let r = createMsCc1SimulationRunner(structuredClone(level));");
push("  const flipSeg = bfs(r, 200, 4_000_000, (x) => x.playerState.hasFlippers, { includeTicksInKey: false });");
push("  if (flipSeg) {");
push('    console.log("flippers", flipSeg.seq.length, "ticks", flipSeg.ticks);');
push("    r = apply(r, flipSeg.seq);");
push("    const exitSeg = bfs(r, 250, 4_000_000, (x) => x.completed, { includeTicksInKey: false });");
push("    if (exitSeg) {");
push("      const full = [...flipSeg.seq, ...exitSeg.seq];");
push("      const verify = apply(createMsCc1SimulationRunner(structuredClone(level)), full);");
push("      result = {");
push("        seq: full,");
push("        ticks: verify.buttonPressCtx.moveBoundary,");
push("        rem: msSecondsRemaining(TIME_LIMIT, verify.buttonPressCtx.moveBoundary),");
push("        bold: meetsBold(verify.buttonPressCtx.moveBoundary),");
push("      };");
push('      result = report("segmentedBfs", result);');
push("    }");
push("  }");
push("}");
push("");
push("if (!result) {");
push('  console.log("\\n=== Manual prefixes + BFS ===");');
push("  for (const pre of [");
push('    "LLLLUUUUUUUUUUUUUUUUUUUUUUU",');
push('    "LLLLUUUUUUUUUUUUUUUUUUUUUUUR",');
push('    "RRRRRRRRRRRRRRRRRRRRRRRRRRR",');
push("  ]) {");
push("    const opener = lettersToDirs(pre);");
push("    let r = apply(createMsCc1SimulationRunner(structuredClone(level)), opener);");
push("    if (r.completed) {");
push("      result = {");
push("        seq: opener,");
push("        ticks: r.buttonPressCtx.moveBoundary,");
push("        rem: msSecondsRemaining(TIME_LIMIT, r.buttonPressCtx.moveBoundary),");
push("        bold: meetsBold(r.buttonPressCtx.moveBoundary),");
push("      };");
push('      report("manual", result);');
push("      break;");
push("    }");
push("    if (r.playerDied) continue;");
push('    console.log("prefix", pre.length, "pos", r.gx, r.gy, "flip", r.playerState.hasFlippers);');
push("    const rest = bfs(r, 300, 3_000_000, (x) => x.completed, { includeTicksInKey: false });");
push("    if (rest) {");
push("      const full = [...opener, ...rest.seq];");
push("      const verify = apply(createMsCc1SimulationRunner(structuredClone(level)), full);");
push("      result = {");
push("        seq: full,");
push("        ticks: verify.buttonPressCtx.moveBoundary,");
push("        rem: msSecondsRemaining(TIME_LIMIT, verify.buttonPressCtx.moveBoundary),");
push("        bold: meetsBold(verify.buttonPressCtx.moveBoundary),");
push("      };");
push('      result = report("manual+bfs", result);');
push("      break;");
push("    }");
push("  }");
push("}");
push("");
push("if (!result) {");
push('  console.log("FAILED");');
push("  process.exit(1);");
push("}");
push("");
push('const outPath = path.join(root, ".tmp/level018-bold-solution.json");');
push("fs.mkdirSync(path.dirname(outPath), { recursive: true });");
push("fs.writeFileSync(outPath, JSON.stringify({ ...result, moves: encodeSolutionMoves(result.seq) }, null, 2) + \"\\n\");");
push('console.log("Wrote", outPath);');
fs.writeFileSync(target, lines.join("\n") + "\n");
console.log("wrote", target, lines.length);
